const countries = [
  { abbrev2: 'AF', abbrev3: 'AFG', dialingCode: '93', name: 'Afghanistan' },
  { abbrev2: 'AL', abbrev3: 'ALB', dialingCode: '355', name: 'Albania' },
  { abbrev2: 'DZ', abbrev3: 'DZA', dialingCode: '213', name: 'Algeria' },
  { abbrev2: 'AS', abbrev3: 'ASM', dialingCode: '1-684', name: 'American Samoa' },
  { abbrev2: 'AD', abbrev3: 'AND', dialingCode: '376', name: 'Andorra' },
  { abbrev2: 'AO', abbrev3: 'AGO', dialingCode: '244', name: 'Angola' },
  { abbrev2: 'AI', abbrev3: 'AIA', dialingCode: '1-264', name: 'Anguilla' },
  { abbrev2: 'AQ', abbrev3: 'ATA', dialingCode: '672', name: 'Antarctica' },
  { abbrev2: 'AG', abbrev3: 'ATG', dialingCode: '1-268', name: 'Antigua and Barbuda' },
  { abbrev2: 'AR', abbrev3: 'ARG', dialingCode: '54', name: 'Argentina' },
  { abbrev2: 'AM', abbrev3: 'ARM', dialingCode: '374', name: 'Armenia' },
  { abbrev2: 'AW', abbrev3: 'ABW', dialingCode: '297', name: 'Aruba' },
  { abbrev2: 'AU', abbrev3: 'AUS', dialingCode: '61', name: 'Australia' },
  { abbrev2: 'AT', abbrev3: 'AUT', dialingCode: '43', name: 'Austria' },
  { abbrev2: 'AZ', abbrev3: 'AZE', dialingCode: '994', name: 'Azerbaijan' },
  { abbrev2: 'BS', abbrev3: 'BHS', dialingCode: '1-242', name: 'Bahamas' },
  { abbrev2: 'BH', abbrev3: 'BHR', dialingCode: '973', name: 'Bahrain' },
  { abbrev2: 'BD', abbrev3: 'BGD', dialingCode: '880', name: 'Bangladesh' },
  { abbrev2: 'BB', abbrev3: 'BRB', dialingCode: '1-246', name: 'Barbados' },
  { abbrev2: 'BY', abbrev3: 'BLR', dialingCode: '375', name: 'Belarus' },
  { abbrev2: 'BE', abbrev3: 'BEL', dialingCode: '32', name: 'Belgium' },
  { abbrev2: 'BZ', abbrev3: 'BLZ', dialingCode: '501', name: 'Belize' },
  { abbrev2: 'BJ', abbrev3: 'BEN', dialingCode: '229', name: 'Benin' },
  { abbrev2: 'BM', abbrev3: 'BMU', dialingCode: '1-441', name: 'Bermuda' },
  { abbrev2: 'BT', abbrev3: 'BTN', dialingCode: '975', name: 'Bhutan' },
  { abbrev2: 'BO', abbrev3: 'BOL', dialingCode: '591', name: 'Bolivia' },
  { abbrev2: 'BQ', abbrev3: 'BES', dialingCode: '599', name: 'Bonaire' },
  { abbrev2: 'BA', abbrev3: 'BIH', dialingCode: '387', name: 'Bosnia and Herzegovina' },
  { abbrev2: 'BW', abbrev3: 'BWA', dialingCode: '267', name: 'Botswana' },
  { abbrev2: 'BV', abbrev3: 'BVT', dialingCode: '47', name: 'Bouvet Island' },
  { abbrev2: 'BR', abbrev3: 'BRA', dialingCode: '55', name: 'Brazil' },
  { abbrev2: 'IO', abbrev3: 'IOT', dialingCode: '246', name: 'British Indian Ocean Territory' },
  { abbrev2: 'BN', abbrev3: 'BRN', dialingCode: '673', name: 'Brunei Darussalam' },
  { abbrev2: 'BG', abbrev3: 'BGR', dialingCode: '359', name: 'Bulgaria' },
  { abbrev2: 'BF', abbrev3: 'BFA', dialingCode: '226', name: 'Burkina Faso' },
  { abbrev2: 'BI', abbrev3: 'BDI', dialingCode: '257', name: 'Burundi' },
  { abbrev2: 'KH', abbrev3: 'KHM', dialingCode: '855', name: 'Cambodia' },
  { abbrev2: 'CM', abbrev3: 'CMR', dialingCode: '237', name: 'Cameroon' },
  { abbrev2: 'CA', abbrev3: 'CAN', dialingCode: '1', name: 'Canada' },
  { abbrev2: 'CV', abbrev3: 'CPV', dialingCode: '238', name: 'Cape Verde' },
  { abbrev2: 'KY', abbrev3: 'CYM', dialingCode: '1-345', name: 'Cayman Islands' },
  { abbrev2: 'CF', abbrev3: 'CAF', dialingCode: '236', name: 'Central African Republic' },
  { abbrev2: 'TD', abbrev3: 'TCD', dialingCode: '235', name: 'Chad' },
  { abbrev2: 'CL', abbrev3: 'CHL', dialingCode: '56', name: 'Chile' },
  { abbrev2: 'CN', abbrev3: 'CHN', dialingCode: '86', name: 'China' },
  { abbrev2: 'CX', abbrev3: 'CXR', dialingCode: '61', name: 'Christmas Island' },
  { abbrev2: 'CC', abbrev3: 'CCK', dialingCode: '61', name: 'Cocos (Keeling) Islands' },
  { abbrev2: 'CO', abbrev3: 'COL', dialingCode: '57', name: 'Colombia' },
  { abbrev2: 'KM', abbrev3: 'COM', dialingCode: '269', name: 'Comoros' },
  { abbrev2: 'CG', abbrev3: 'COG', dialingCode: '242', name: 'Congo' },
  { abbrev2: 'CD', abbrev3: 'COD', dialingCode: '243', name: 'Democratic Republic of the Congo' },
  { abbrev2: 'CK', abbrev3: 'COK', dialingCode: '682', name: 'Cook Islands' },
  { abbrev2: 'CR', abbrev3: 'CRI', dialingCode: '506', name: 'Costa Rica' },
  { abbrev2: 'HR', abbrev3: 'HRV', dialingCode: '385', name: 'Croatia' },
  { abbrev2: 'CU', abbrev3: 'CUB', dialingCode: '53', name: 'Cuba' },
  { abbrev2: 'CW', abbrev3: 'CUW', dialingCode: '599', name: 'CuraÃ§ao' },
  { abbrev2: 'CY', abbrev3: 'CYP', dialingCode: '357', name: 'Cyprus' },
  { abbrev2: 'CZ', abbrev3: 'CZE', dialingCode: '420', name: 'Czech Republic' },
  { abbrev2: 'CI', abbrev3: 'CIV', dialingCode: '225', name: "CÃ´te d'Ivoire" },
  { abbrev2: 'DK', abbrev3: 'DNK', dialingCode: '45', name: 'Denmark' },
  { abbrev2: 'DJ', abbrev3: 'DJI', dialingCode: '253', name: 'Djibouti' },
  { abbrev2: 'DM', abbrev3: 'DMA', dialingCode: '1-767', name: 'Dominica' },
  { abbrev2: 'DO', abbrev3: 'DOM', dialingCode: '1-809,1-829,1-849', name: 'Dominican Republic' },
  { abbrev2: 'EC', abbrev3: 'ECU', dialingCode: '593', name: 'Ecuador' },
  { abbrev2: 'EG', abbrev3: 'EGY', dialingCode: '20', name: 'Egypt' },
  { abbrev2: 'SV', abbrev3: 'SLV', dialingCode: '503', name: 'El Salvador' },
  { abbrev2: 'GQ', abbrev3: 'GNQ', dialingCode: '240', name: 'Equatorial Guinea' },
  { abbrev2: 'ER', abbrev3: 'ERI', dialingCode: '291', name: 'Eritrea' },
  { abbrev2: 'EE', abbrev3: 'EST', dialingCode: '372', name: 'Estonia' },
  { abbrev2: 'ET', abbrev3: 'ETH', dialingCode: '251', name: 'Ethiopia' },
  { abbrev2: 'FK', abbrev3: 'FLK', dialingCode: '500', name: 'Falkland Islands (Malvinas)' },
  { abbrev2: 'FO', abbrev3: 'FRO', dialingCode: '298', name: 'Faroe Islands' },
  { abbrev2: 'FJ', abbrev3: 'FJI', dialingCode: '679', name: 'Fiji' },
  { abbrev2: 'FI', abbrev3: 'FIN', dialingCode: '358', name: 'Finland' },
  { abbrev2: 'FR', abbrev3: 'FRA', dialingCode: '33', name: 'France' },
  { abbrev2: 'GF', abbrev3: 'GUF', dialingCode: '594', name: 'French Guiana' },
  { abbrev2: 'PF', abbrev3: 'PYF', dialingCode: '689', name: 'French Polynesia' },
  { abbrev2: 'TF', abbrev3: 'ATF', dialingCode: '262', name: 'French Southern Territories' },
  { abbrev2: 'GA', abbrev3: 'GAB', dialingCode: '241', name: 'Gabon' },
  { abbrev2: 'GM', abbrev3: 'GMB', dialingCode: '220', name: 'Gambia' },
  { abbrev2: 'GE', abbrev3: 'GEO', dialingCode: '995', name: 'Georgia' },
  { abbrev2: 'DE', abbrev3: 'DEU', dialingCode: '49', name: 'Germany' },
  { abbrev2: 'GH', abbrev3: 'GHA', dialingCode: '233', name: 'Ghana' },
  { abbrev2: 'GI', abbrev3: 'GIB', dialingCode: '350', name: 'Gibraltar' },
  { abbrev2: 'GR', abbrev3: 'GRC', dialingCode: '30', name: 'Greece' },
  { abbrev2: 'GL', abbrev3: 'GRL', dialingCode: '299', name: 'Greenland' },
  { abbrev2: 'GD', abbrev3: 'GRD', dialingCode: '1-473', name: 'Grenada' },
  { abbrev2: 'GP', abbrev3: 'GLP', dialingCode: '590', name: 'Guadeloupe' },
  { abbrev2: 'GU', abbrev3: 'GUM', dialingCode: '1-671', name: 'Guam' },
  { abbrev2: 'GT', abbrev3: 'GTM', dialingCode: '502', name: 'Guatemala' },
  { abbrev2: 'GG', abbrev3: 'GGY', dialingCode: '44', name: 'Guernsey' },
  { abbrev2: 'GN', abbrev3: 'GIN', dialingCode: '224', name: 'Guinea' },
  { abbrev2: 'GW', abbrev3: 'GNB', dialingCode: '245', name: 'Guinea-Bissau' },
  { abbrev2: 'GY', abbrev3: 'GUY', dialingCode: '592', name: 'Guyana' },
  { abbrev2: 'HT', abbrev3: 'HTI', dialingCode: '509', name: 'Haiti' },
  { abbrev2: 'HM', abbrev3: 'HMD', dialingCode: '672', name: 'Heard Island and McDonald Mcdonald Islands' },
  { abbrev2: 'VA', abbrev3: 'VAT', dialingCode: '379', name: 'Holy See (Vatican City State)' },
  { abbrev2: 'HN', abbrev3: 'HND', dialingCode: '504', name: 'Honduras' },
  { abbrev2: 'HK', abbrev3: 'HKG', dialingCode: '852', name: 'Hong Kong' },
  { abbrev2: 'HU', abbrev3: 'HUN', dialingCode: '36', name: 'Hungary' },
  { abbrev2: 'IS', abbrev3: 'ISL', dialingCode: '354', name: 'Iceland' },
  { abbrev2: 'IN', abbrev3: 'IND', dialingCode: '91', name: 'India' },
  { abbrev2: 'ID', abbrev3: 'IDN', dialingCode: '62', name: 'Indonesia' },
  { abbrev2: 'IR', abbrev3: 'IRN', dialingCode: '98', name: 'Iran, Islamic Republic of' },
  { abbrev2: 'IQ', abbrev3: 'IRQ', dialingCode: '964', name: 'Iraq' },
  { abbrev2: 'IE', abbrev3: 'IRL', dialingCode: '353', name: 'Ireland' },
  { abbrev2: 'IM', abbrev3: 'IMN', dialingCode: '44', name: 'Isle of Man' },
  { abbrev2: 'IL', abbrev3: 'ISR', dialingCode: '972', name: 'Israel' },
  { abbrev2: 'IT', abbrev3: 'ITA', dialingCode: '39', name: 'Italy' },
  { abbrev2: 'JM', abbrev3: 'JAM', dialingCode: '1-876', name: 'Jamaica' },
  { abbrev2: 'JP', abbrev3: 'JPN', dialingCode: '81', name: 'Japan' },
  { abbrev2: 'JE', abbrev3: 'JEY', dialingCode: '44', name: 'Jersey' },
  { abbrev2: 'JO', abbrev3: 'JOR', dialingCode: '962', name: 'Jordan' },
  { abbrev2: 'KZ', abbrev3: 'KAZ', dialingCode: '7', name: 'Kazakhstan' },
  { abbrev2: 'KE', abbrev3: 'KEN', dialingCode: '254', name: 'Kenya' },
  { abbrev2: 'KI', abbrev3: 'KIR', dialingCode: '686', name: 'Kiribati' },
  { abbrev2: 'KP', abbrev3: 'PRK', dialingCode: '850', name: "Korea, Democratic People's Republic of" },
  { abbrev2: 'KR', abbrev3: 'KOR', dialingCode: '82', name: 'Korea, Republic of' },
  { abbrev2: 'KW', abbrev3: 'KWT', dialingCode: '965', name: 'Kuwait' },
  { abbrev2: 'KG', abbrev3: 'KGZ', dialingCode: '996', name: 'Kyrgyzstan' },
  { abbrev2: 'LA', abbrev3: 'LAO', dialingCode: '856', name: "Lao People's Democratic Republic" },
  { abbrev2: 'LV', abbrev3: 'LVA', dialingCode: '371', name: 'Latvia' },
  { abbrev2: 'LB', abbrev3: 'LBN', dialingCode: '961', name: 'Lebanon' },
  { abbrev2: 'LS', abbrev3: 'LSO', dialingCode: '266', name: 'Lesotho' },
  { abbrev2: 'LR', abbrev3: 'LBR', dialingCode: '231', name: 'Liberia' },
  { abbrev2: 'LY', abbrev3: 'LBY', dialingCode: '218', name: 'Libya' },
  { abbrev2: 'LI', abbrev3: 'LIE', dialingCode: '423', name: 'Liechtenstein' },
  { abbrev2: 'LT', abbrev3: 'LTU', dialingCode: '370', name: 'Lithuania' },
  { abbrev2: 'LU', abbrev3: 'LUX', dialingCode: '352', name: 'Luxembourg' },
  { abbrev2: 'MO', abbrev3: 'MAC', dialingCode: '853', name: 'Macao' },
  { abbrev2: 'MK', abbrev3: 'MKD', dialingCode: '389', name: 'Macedonia, the Former Yugoslav Republic of' },
  { abbrev2: 'MG', abbrev3: 'MDG', dialingCode: '261', name: 'Madagascar' },
  { abbrev2: 'MW', abbrev3: 'MWI', dialingCode: '265', name: 'Malawi' },
  { abbrev2: 'MY', abbrev3: 'MYS', dialingCode: '60', name: 'Malaysia' },
  { abbrev2: 'MV', abbrev3: 'MDV', dialingCode: '960', name: 'Maldives' },
  { abbrev2: 'ML', abbrev3: 'MLI', dialingCode: '223', name: 'Mali' },
  { abbrev2: 'MT', abbrev3: 'MLT', dialingCode: '356', name: 'Malta' },
  { abbrev2: 'MH', abbrev3: 'MHL', dialingCode: '692', name: 'Marshall Islands' },
  { abbrev2: 'MQ', abbrev3: 'MTQ', dialingCode: '596', name: 'Martinique' },
  { abbrev2: 'MR', abbrev3: 'MRT', dialingCode: '222', name: 'Mauritania' },
  { abbrev2: 'MU', abbrev3: 'MUS', dialingCode: '230', name: 'Mauritius' },
  { abbrev2: 'YT', abbrev3: 'MYT', dialingCode: '262', name: 'Mayotte' },
  { abbrev2: 'MX', abbrev3: 'MEX', dialingCode: '52', name: 'Mexico' },
  { abbrev2: 'FM', abbrev3: 'FSM', dialingCode: '691', name: 'Micronesia, Federated States of' },
  { abbrev2: 'MD', abbrev3: 'MDA', dialingCode: '373', name: 'Moldova, Republic of' },
  { abbrev2: 'MC', abbrev3: 'MCO', dialingCode: '377', name: 'Monaco' },
  { abbrev2: 'MN', abbrev3: 'MNG', dialingCode: '976', name: 'Mongolia' },
  { abbrev2: 'ME', abbrev3: 'MNE', dialingCode: '382', name: 'Montenegro' },
  { abbrev2: 'MS', abbrev3: 'MSR', dialingCode: '1-664', name: 'Montserrat' },
  { abbrev2: 'MA', abbrev3: 'MAR', dialingCode: '212', name: 'Morocco' },
  { abbrev2: 'MZ', abbrev3: 'MOZ', dialingCode: '258', name: 'Mozambique' },
  { abbrev2: 'MM', abbrev3: 'MMR', dialingCode: '95', name: 'Myanmar' },
  { abbrev2: 'NA', abbrev3: 'NAM', dialingCode: '264', name: 'Namibia' },
  { abbrev2: 'NR', abbrev3: 'NRU', dialingCode: '674', name: 'Nauru' },
  { abbrev2: 'NP', abbrev3: 'NPL', dialingCode: '977', name: 'Nepal' },
  { abbrev2: 'NL', abbrev3: 'NLD', dialingCode: '31', name: 'Netherlands' },
  { abbrev2: 'NC', abbrev3: 'NCL', dialingCode: '687', name: 'New Caledonia' },
  { abbrev2: 'NZ', abbrev3: 'NZL', dialingCode: '64', name: 'New Zealand' },
  { abbrev2: 'NI', abbrev3: 'NIC', dialingCode: '505', name: 'Nicaragua' },
  { abbrev2: 'NE', abbrev3: 'NER', dialingCode: '227', name: 'Niger' },
  { abbrev2: 'NG', abbrev3: 'NGA', dialingCode: '234', name: 'Nigeria' },
  { abbrev2: 'NU', abbrev3: 'NIU', dialingCode: '683', name: 'Niue' },
  { abbrev2: 'NF', abbrev3: 'NFK', dialingCode: '672', name: 'Norfolk Island' },
  { abbrev2: 'MP', abbrev3: 'MNP', dialingCode: '1-670', name: 'Northern Mariana Islands' },
  { abbrev2: 'NO', abbrev3: 'NOR', dialingCode: '47', name: 'Norway' },
  { abbrev2: 'OM', abbrev3: 'OMN', dialingCode: '968', name: 'Oman' },
  { abbrev2: 'PK', abbrev3: 'PAK', dialingCode: '92', name: 'Pakistan' },
  { abbrev2: 'PW', abbrev3: 'PLW', dialingCode: '680', name: 'Palau' },
  { abbrev2: 'PS', abbrev3: 'PSE', dialingCode: '970', name: 'Palestine, State of' },
  { abbrev2: 'PA', abbrev3: 'PAN', dialingCode: '507', name: 'Panama' },
  { abbrev2: 'PG', abbrev3: 'PNG', dialingCode: '675', name: 'Papua New Guinea' },
  { abbrev2: 'PY', abbrev3: 'PRY', dialingCode: '595', name: 'Paraguay' },
  { abbrev2: 'PE', abbrev3: 'PER', dialingCode: '51', name: 'Peru' },
  { abbrev2: 'PH', abbrev3: 'PHL', dialingCode: '63', name: 'Philippines' },
  { abbrev2: 'PN', abbrev3: 'PCN', dialingCode: '870', name: 'Pitcairn' },
  { abbrev2: 'PL', abbrev3: 'POL', dialingCode: '48', name: 'Poland' },
  { abbrev2: 'PT', abbrev3: 'PRT', dialingCode: '351', name: 'Portugal' },
  { abbrev2: 'PR', abbrev3: 'PRI', dialingCode: '1', name: 'Puerto Rico' },
  { abbrev2: 'QA', abbrev3: 'QAT', dialingCode: '974', name: 'Qatar' },
  { abbrev2: 'RO', abbrev3: 'ROU', dialingCode: '40', name: 'Romania' },
  { abbrev2: 'RU', abbrev3: 'RUS', dialingCode: '7', name: 'Russian Federation' },
  { abbrev2: 'RW', abbrev3: 'RWA', dialingCode: '250', name: 'Rwanda' },
  { abbrev2: 'RE', abbrev3: 'REU', dialingCode: '262', name: 'Reunion' },
  { abbrev2: 'BL', abbrev3: 'BLM', dialingCode: '590', name: 'Saint Barthalemy' },
  { abbrev2: 'SH', abbrev3: 'SHN', dialingCode: '290', name: 'Saint Helena' },
  { abbrev2: 'KN', abbrev3: 'KNA', dialingCode: '1-869', name: 'Saint Kitts and Nevis' },
  { abbrev2: 'LC', abbrev3: 'LCA', dialingCode: '1-758', name: 'Saint Lucia' },
  { abbrev2: 'MF', abbrev3: 'MAF', dialingCode: '590', name: 'Saint Martin (French part)' },
  { abbrev2: 'PM', abbrev3: 'SPM', dialingCode: '508', name: 'Saint Pierre and Miquelon' },
  { abbrev2: 'VC', abbrev3: 'VCT', dialingCode: '1-784', name: 'Saint Vincent and the Grenadines' },
  { abbrev2: 'WS', abbrev3: 'WSM', dialingCode: '685', name: 'Samoa' },
  { abbrev2: 'SM', abbrev3: 'SMR', dialingCode: '378', name: 'San Marino' },
  { abbrev2: 'ST', abbrev3: 'STP', dialingCode: '239', name: 'Sao Tome and Principe' },
  { abbrev2: 'SA', abbrev3: 'SAU', dialingCode: '966', name: 'Saudi Arabia' },
  { abbrev2: 'SN', abbrev3: 'SEN', dialingCode: '221', name: 'Senegal' },
  { abbrev2: 'RS', abbrev3: 'SRB', dialingCode: '381', name: 'Serbia' },
  { abbrev2: 'SC', abbrev3: 'SYC', dialingCode: '248', name: 'Seychelles' },
  { abbrev2: 'SL', abbrev3: 'SLE', dialingCode: '232', name: 'Sierra Leone' },
  { abbrev2: 'SG', abbrev3: 'SGP', dialingCode: '65', name: 'Singapore' },
  { abbrev2: 'SX', abbrev3: 'SXM', dialingCode: '1-721', name: 'Sint Maarten (Dutch part)' },
  { abbrev2: 'SK', abbrev3: 'SVK', dialingCode: '421', name: 'Slovakia' },
  { abbrev2: 'SI', abbrev3: 'SVN', dialingCode: '386', name: 'Slovenia' },
  { abbrev2: 'SB', abbrev3: 'SLB', dialingCode: '677', name: 'Solomon Islands' },
  { abbrev2: 'SO', abbrev3: 'SOM', dialingCode: '252', name: 'Somalia' },
  { abbrev2: 'ZA', abbrev3: 'ZAF', dialingCode: '27', name: 'South Africa' },
  { abbrev2: 'GS', abbrev3: 'SGS', dialingCode: '500', name: 'South Georgia and the South Sandwich Islands' },
  { abbrev2: 'SS', abbrev3: 'SSD', dialingCode: '211', name: 'South Sudan' },
  { abbrev2: 'ES', abbrev3: 'ESP', dialingCode: '34', name: 'Spain' },
  { abbrev2: 'LK', abbrev3: 'LKA', dialingCode: '94', name: 'Sri Lanka' },
  { abbrev2: 'SD', abbrev3: 'SDN', dialingCode: '249', name: 'Sudan' },
  { abbrev2: 'SR', abbrev3: 'SUR', dialingCode: '597', name: 'Suriname' },
  { abbrev2: 'SJ', abbrev3: 'SJM', dialingCode: '47', name: 'Svalbard and Jan Mayen' },
  { abbrev2: 'SZ', abbrev3: 'SWZ', dialingCode: '268', name: 'Swaziland' },
  { abbrev2: 'SE', abbrev3: 'SWE', dialingCode: '46', name: 'Sweden' },
  { abbrev2: 'CH', abbrev3: 'CHE', dialingCode: '41', name: 'Switzerland' },
  { abbrev2: 'SY', abbrev3: 'SYR', dialingCode: '963', name: 'Syrian Arab Republic' },
  { abbrev2: 'TW', abbrev3: 'TWN', dialingCode: '886', name: 'Taiwan, Province of China' },
  { abbrev2: 'TJ', abbrev3: 'TJK', dialingCode: '992', name: 'Tajikistan' },
  { abbrev2: 'TZ', abbrev3: 'TZA', dialingCode: '255', name: 'United Republic of Tanzania' },
  { abbrev2: 'TH', abbrev3: 'THA', dialingCode: '66', name: 'Thailand' },
  { abbrev2: 'TL', abbrev3: 'TLS', dialingCode: '670', name: 'Timor-Leste' },
  { abbrev2: 'TG', abbrev3: 'TGO', dialingCode: '228', name: 'Togo' },
  { abbrev2: 'TK', abbrev3: 'TKL', dialingCode: '690', name: 'Tokelau' },
  { abbrev2: 'TO', abbrev3: 'TON', dialingCode: '676', name: 'Tonga' },
  { abbrev2: 'TT', abbrev3: 'TTO', dialingCode: '1-868', name: 'Trinidad and Tobago' },
  { abbrev2: 'TN', abbrev3: 'TUN', dialingCode: '216', name: 'Tunisia' },
  { abbrev2: 'TR', abbrev3: 'TUR', dialingCode: '90', name: 'Turkey' },
  { abbrev2: 'TM', abbrev3: 'TKM', dialingCode: '993', name: 'Turkmenistan' },
  { abbrev2: 'TC', abbrev3: 'TCA', dialingCode: '1-649', name: 'Turks and Caicos Islands' },
  { abbrev2: 'TV', abbrev3: 'TUV', dialingCode: '688', name: 'Tuvalu' },
  { abbrev2: 'UG', abbrev3: 'UGA', dialingCode: '256', name: 'Uganda' },
  { abbrev2: 'UA', abbrev3: 'UKR', dialingCode: '380', name: 'Ukraine' },
  { abbrev2: 'AE', abbrev3: 'ARE', dialingCode: '971', name: 'United Arab Emirates' },
  { abbrev2: 'GB', abbrev3: 'GBR', dialingCode: '44', name: 'United Kingdom' },
  { abbrev2: 'US', abbrev3: 'USA', dialingCode: '1', name: 'United States' },
  { abbrev2: 'UM', abbrev3: 'UMI', dialingCode: '1', name: 'United States Minor Outlying Islands' },
  { abbrev2: 'UY', abbrev3: 'URY', dialingCode: '598', name: 'Uruguay' },
  { abbrev2: 'UZ', abbrev3: 'UZB', dialingCode: '998', name: 'Uzbekistan' },
  { abbrev2: 'VU', abbrev3: 'VUT', dialingCode: '678', name: 'Vanuatu' },
  { abbrev2: 'VE', abbrev3: 'VEN', dialingCode: '58', name: 'Venezuela' },
  { abbrev2: 'VN', abbrev3: 'VNM', dialingCode: '84', name: 'Viet Nam' },
  { abbrev2: 'VG', abbrev3: 'VGB', dialingCode: '1-284', name: 'British Virgin Islands' },
  { abbrev2: 'VI', abbrev3: 'VIR', dialingCode: '1-340', name: 'US Virgin Islands' },
  { abbrev2: 'WF', abbrev3: 'WLF', dialingCode: '681', name: 'Wallis and Futuna' },
  { abbrev2: 'EH', abbrev3: 'ESH', dialingCode: '212', name: 'Western Sahara' },
  { abbrev2: 'YE', abbrev3: 'YEM', dialingCode: '967', name: 'Yemen' },
  { abbrev2: 'ZM', abbrev3: 'ZMB', dialingCode: '260', name: 'Zambia' },
  { abbrev2: 'ZW', abbrev3: 'ZWE', dialingCode: '263', name: 'Zimbabwe' },
  { abbrev2: 'AX', abbrev3: 'ALA', dialingCode: '358', name: 'Aland Islands' },
]

export default countries
